Make app
reckyy/app_sinatra pull request #1
Opened 2023-10-01 07:11 UTC by reckyy

ご確認のほどよろしくお願いします！

2023-10-06 03:26 UTC, u1tnk requested changes

2023-10-06 03:26 UTC, u1tnk commented on db.json
> +[{"id":1,"title":"テスト１","content":"メモ１"},{"id":2,"title":"テスト２","content":"メモ２"},{"id":3,"title":"テスト3","content":"メモ3"},{"id":4,"title":"テスト4","content":"メモ4"},{"id":5,"title":"テスト5","content":"メモ5"
データファイルはgit管理にしないようにしてください。
変更が頻繁で管理が大変であることなどが主な理由です。
初期セットアップスクリプトなどで作成するか、データファイルは無いところから動くようにプログラムを作るのが一般的です。
本プラクティスでは後者で行なってください。

2023-10-06 03:26 UTC, u1tnk commented on main.rb
> +    json[@id - 1] = { 'id' => @id, 'title' => memo_title, 'content' => memo_content }
idの部分にデータを書き込めば良いと思うのですが、どうして マイナス1するんでしょうか？

2023-10-06 03:26 UTC, u1tnk commented on main.rb
> +def judge_request(json)
まず、名前が良くないです。
judge_requestとありますが、requestの種類から判断して色々やっていますが、色々の部分の方がこのメソッドのメインのタスクですが、重要な方が省略されてしまっています。

なぜこうなるかというと、このメソッドに色々やらせすぎというのがあります。
- 入力のescape
- methodを判断してデータを挿入or上書きする
- idの採番

そもそも methodを判断してpost/patchに来てるのでデータの編集はそこでやれば良いと思います。

2023-10-06 03:26 UTC, u1tnk commented on main.rb
> +  memo_title = CGI.escapeHTML(params['title'])
escapeしたデータを保存するのは良くないです。escapeは完全に元に戻せない処理なのでデータを失うおそれがあります。
escapeはhtml上でscriptなどを動作させないためのものなのでhtmlに表示させるときのみ行いましょう。

2023-10-06 03:26 UTC, u1tnk commented on main.rb
> +    id = json.size + 1
この処理だとdeleteした後に追加すると重複しませんか？

2023-10-06 03:26 UTC, u1tnk commented on main.rb
> +  @json = read_json
jsonはデータフォーマットの名前であって、変数名としては適当ではありません。
なんのデータが入っているか？がわかる名前が良いですね。

2023-10-06 03:26 UTC, u1tnk commented on main.rb
> +  File.write('db.json', new_data)
db.jsonは複数書いてミスると重大ですし、定数にして同じことを明示した方が良いと思います。

2023-10-06 03:26 UTC, u1tnk commented on main.rb
> +  new_data = JSON.dump(old_data)
patch/postは共通化されていますが、deleteも jsonから読み出したデータを書き込むという点でほぼ同じなので共通化できるのでは無いでしょうか？

2023-10-08 01:10 UTC, reckyy commented on db.json
> +[{"id":1,"title":"テスト１","content":"メモ１"},{"id":2,"title":"テスト２","content":"メモ２"},{"id":3,"title":"テスト3","content":"メモ3"},{"id":4,"title":"テスト4","content":"メモ4"},{"id":5,"title":"テスト5","content":"メモ5"
承知いたしました。
`before`内に、もしdb.jsonが存在しなかったら、生成するように変更しました！

2023-10-08 02:57 UTC, reckyy commented on main.rb
> +    json[@id - 1] = { 'id' => @id, 'title' => memo_title, 'content' => memo_content }
配列でdb.jsonを管理していたため、インデックスの都合で-1していました。
ですが、ご指摘からdb.jsonの形式をArrayからHashに変更しました。
それに伴い、`-1`はなくなりました。

2023-10-08 08:26 UTC, reckyy commented on main.rb
> +  memo_title = CGI.escapeHTML(params['title'])
承知しました。
escapeする場所をmain.rbでdb.jsonに保存するときでは無く、各viewで表示するときに変更しました。

2023-10-08 08:40 UTC, reckyy commented on main.rb
> +  @json = read_json
不適切でした。。
`@all_memos`に変更しました！

2023-10-08 08:50 UTC, reckyy commented on main.rb
> +  File.write('db.json', new_data)
修正いたしました！

2023-10-08 09:06 UTC, reckyy commented on main.rb
> +def judge_request(json)
確かに詰め込みすぎて、なんでもやろうとしていました。。

> そもそも methodを判断してpost/patchに来てるのでデータの編集はそこでやれば良いと思います。

その通りです。
不要なメソッド、`judge_request` `edit_db`を削除しました。

2023-10-08 09:31 UTC, reckyy commented on main.rb
> +    id = json.size + 1
修正に伴い、重複は無くなったと思います！

2023-10-08 11:45 UTC, reckyy commented on main.rb
> +  new_data = JSON.dump(old_data)
一応、書き込む部分だけを共通化し`write_json`でメソッド化しました！

2023-10-08 16:10 UTC, u1tnk commented on main.rb
> +    json[@id - 1] = { 'id' => @id, 'title' => memo_title, 'content' => memo_content }
ああ、hashじゃなくてArrayだったんですね。了解ですー

2023-10-08 16:33 UTC, u1tnk requested changes

2023-10-08 16:33 UTC, u1tnk commented on main.rb
> +DB = 'db.json'
ちょっと抽象的過ぎますね。
DBという変数があったらデータベースのインスタンスかな？と思います。
`DB.find(id)` など便利メソッドがあるイメージですね。

これは「データベースを保存するファイル名(厳密にはファイルパス)」 となりますので、分かるように、でも長すぎないようにつけてください。

2023-10-08 16:33 UTC, u1tnk commented on main.rb
> +  id = old_data.empty? ? 1 : old_data.keys.last.to_i + 1
`old_data.keys.last.to_i`

たぶん問題無いんですが、hashの最後が最大のキーの値だと保証されてないと正しくないコードでちょっと不安になっちゃいますね。

単純にkey全部の中で最大を取るようにしてみましょう。

2023-10-08 16:33 UTC, u1tnk commented on main.rb
> +  @id = id
viewには最低限のデータを渡したいので、全部のデータとidを渡すのではなく、対象のメモのデータのみ渡すようにしましょう。

2023-10-09 07:48 UTC, reckyy commented on main.rb
> +DB = 'db.json'
なるほど、、想定してませんでした😭
パスを表すため、`db_path`と変更しました！

2023-10-09 08:01 UTC, reckyy commented on main.rb
> +  @id = id
`old_data.keys.max_by(&:to_i).to_i`に修正いたしました！

2023-10-09 08:02 UTC, reckyy commented on main.rb
> +  id = old_data.empty? ? 1 : old_data.keys.last.to_i + 1
`old_data.keys.max_by(&:to_i).to_i`に修正いたしました！

2023-10-09 08:43 UTC, reckyy commented on main.rb
> +  @id = id
確かにそうでした。。
該当メモの情報のみ渡すように、変更しました！

2023-10-09 14:16 UTC, u1tnk requested changes

2023-10-09 14:16 UTC, u1tnk commented on main.rb
> +  @id = id
改善しましたが、 memo情報の中に id入っていますよね？ でしたら `@id` 自体要らないと思います。

2023-10-09 14:53 UTC, reckyy commented on main.rb
> +  @id = id
そうでした。。😭`@memo['id']`で取得できますことを失念していました。
自分で気づかないといけないミスでした。
こちらは修正したのですが、修正に伴いなぜかdeleteの処理がうまくいかなくなったので、原因究明に時間がかかってます。明日には再提出します！

2023-10-10 12:55 UTC, reckyy commented on main.rb
> +  @id = id
修正完了しました！

2023-10-10 14:59 UTC, u1tnk approved these changes

2023-10-11 11:48 UTC, merged